listen: localhost:8080

# interceptor type:
#   grpc: send request to specific GRPC plugin
#   response: directly response to the request
#   forward: act as a proxy forwarding request further
interceptors:
  auth-grafana:
    type: grpc
    grpc:
      address: localhost:9090
      timeout: 500ms
  deny:
    type: response
    response:
      status: 401
      body: access is forbidden
      headers:
        X-Verdite-Passed: true
  pass:
    type: forward
    request:
      headers:
        X-Verdite-Passed: true

# https://github.com/gorilla/mux#matching-routes
rules:
  # allow requests to grafana only if they have "X-Grafana-User" header
  - match:
      method: GET
      path: /grafana
    onRequest: ["pass", "deny"]
  # reject requests to google
  - match:
      method: GET
      path: /google
    onRequest: ["deny"]
