listen: localhost:8080

# interceptor types
#   grpc: sends request to external GRPC service before processing further
#   response: stops processing request responsing with specified data
#   forward: forwards request furher updating it if required
interceptors:
  auth-grafana:
    type: grpc
    grpc:
      address: localhost:9090
  watermark:
    type: forward
    request:
      headers:
        X-Verdite-Passed: true
  forbid-access:
    type: response
    response:
      status: 401
      body: Direct access is forbidden

rules:
  # any GET request starting from "/grafana" will be forwarded to external plugin
  - match:
      method: GET
      path: /grafana/*any
    onRequest: ["auth-grafana", "watermark"]
  # any GET request starting from "/google" will be blocked with according response
  - match:
      method: GET
      path: /google
    onRequest: ["forbid-access"]
