listen: localhost:8080

# https://github.com/gorilla/mux#matching-routes
route:
  example:
    host: www.example.com
    path: /qwe
    pathPrefix: /qwe
    methods: ["POST"]
    schemes: ["http"]
    headers: ["X-Requested-With"]
    queries: ["key1", "key2"]

# handler type:
#   grpc: send request to specific GRPC plugin
#   response: directly response to the request
#   forward: act as a proxy forwarding request further
requestHandler:
  external:
    type: grpc
    grpc:
      address: localhost:9090
      timeout: 500ms
  forbid:
    type: response
    response:
      status: 401
      body: access is forbidden
      headers:
        X-Verdite-Passed: true
  modify:
    type: forward
    request:
      headers:
        X-Verdite-Passed: true

rules:
  example:
    requestHandlers: ["external", "modify"]
    parseRequestBody: true
