// Code generated by protoc-gen-go. DO NOT EDIT.
// source: http.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OnRequestOutput_Action int32

const (
	// continue processing request without any modification
	OnRequestOutput_IGNORE OnRequestOutput_Action = 0
	// continue processing request, update it based on .req field
	OnRequestOutput_UPDATE OnRequestOutput_Action = 1
	// reject processing, return response specified in .res
	OnRequestOutput_REJECT OnRequestOutput_Action = 2
)

var OnRequestOutput_Action_name = map[int32]string{
	0: "IGNORE",
	1: "UPDATE",
	2: "REJECT",
}
var OnRequestOutput_Action_value = map[string]int32{
	"IGNORE": 0,
	"UPDATE": 1,
	"REJECT": 2,
}

func (x OnRequestOutput_Action) String() string {
	return proto.EnumName(OnRequestOutput_Action_name, int32(x))
}
func (OnRequestOutput_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_http_29fc2865f8068d5b, []int{1, 0}
}

type OnRequestInput struct {
	Req                  *HTTPRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OnRequestInput) Reset()         { *m = OnRequestInput{} }
func (m *OnRequestInput) String() string { return proto.CompactTextString(m) }
func (*OnRequestInput) ProtoMessage()    {}
func (*OnRequestInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_http_29fc2865f8068d5b, []int{0}
}
func (m *OnRequestInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRequestInput.Unmarshal(m, b)
}
func (m *OnRequestInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRequestInput.Marshal(b, m, deterministic)
}
func (dst *OnRequestInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRequestInput.Merge(dst, src)
}
func (m *OnRequestInput) XXX_Size() int {
	return xxx_messageInfo_OnRequestInput.Size(m)
}
func (m *OnRequestInput) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRequestInput.DiscardUnknown(m)
}

var xxx_messageInfo_OnRequestInput proto.InternalMessageInfo

func (m *OnRequestInput) GetReq() *HTTPRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

type OnRequestOutput struct {
	Action               OnRequestOutput_Action `protobuf:"varint,1,opt,name=action,proto3,enum=proto.OnRequestOutput_Action" json:"action,omitempty"`
	Req                  *HTTPRequest           `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	Res                  *HTTPResponse          `protobuf:"bytes,3,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OnRequestOutput) Reset()         { *m = OnRequestOutput{} }
func (m *OnRequestOutput) String() string { return proto.CompactTextString(m) }
func (*OnRequestOutput) ProtoMessage()    {}
func (*OnRequestOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_http_29fc2865f8068d5b, []int{1}
}
func (m *OnRequestOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnRequestOutput.Unmarshal(m, b)
}
func (m *OnRequestOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnRequestOutput.Marshal(b, m, deterministic)
}
func (dst *OnRequestOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnRequestOutput.Merge(dst, src)
}
func (m *OnRequestOutput) XXX_Size() int {
	return xxx_messageInfo_OnRequestOutput.Size(m)
}
func (m *OnRequestOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_OnRequestOutput.DiscardUnknown(m)
}

var xxx_messageInfo_OnRequestOutput proto.InternalMessageInfo

func (m *OnRequestOutput) GetAction() OnRequestOutput_Action {
	if m != nil {
		return m.Action
	}
	return OnRequestOutput_IGNORE
}

func (m *OnRequestOutput) GetReq() *HTTPRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *OnRequestOutput) GetRes() *HTTPResponse {
	if m != nil {
		return m.Res
	}
	return nil
}

type HTTPRequest struct {
	Method               string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	URL                  string            `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	Headers              map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HTTPRequest) Reset()         { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()    {}
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_http_29fc2865f8068d5b, []int{2}
}
func (m *HTTPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPRequest.Unmarshal(m, b)
}
func (m *HTTPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPRequest.Marshal(b, m, deterministic)
}
func (dst *HTTPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPRequest.Merge(dst, src)
}
func (m *HTTPRequest) XXX_Size() int {
	return xxx_messageInfo_HTTPRequest.Size(m)
}
func (m *HTTPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPRequest proto.InternalMessageInfo

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *HTTPRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HTTPResponse struct {
	Status               uint32            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HTTPResponse) Reset()         { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()    {}
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_http_29fc2865f8068d5b, []int{3}
}
func (m *HTTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPResponse.Unmarshal(m, b)
}
func (m *HTTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPResponse.Marshal(b, m, deterministic)
}
func (dst *HTTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPResponse.Merge(dst, src)
}
func (m *HTTPResponse) XXX_Size() int {
	return xxx_messageInfo_HTTPResponse.Size(m)
}
func (m *HTTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPResponse proto.InternalMessageInfo

func (m *HTTPResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *HTTPResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HTTPResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*OnRequestInput)(nil), "proto.OnRequestInput")
	proto.RegisterType((*OnRequestOutput)(nil), "proto.OnRequestOutput")
	proto.RegisterType((*HTTPRequest)(nil), "proto.HTTPRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.HTTPRequest.HeadersEntry")
	proto.RegisterType((*HTTPResponse)(nil), "proto.HTTPResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.HTTPResponse.HeadersEntry")
	proto.RegisterEnum("proto.OnRequestOutput_Action", OnRequestOutput_Action_name, OnRequestOutput_Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InterceptorClient is the client API for Interceptor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InterceptorClient interface {
	OnRequest(ctx context.Context, in *OnRequestInput, opts ...grpc.CallOption) (*OnRequestOutput, error)
}

type interceptorClient struct {
	cc *grpc.ClientConn
}

func NewInterceptorClient(cc *grpc.ClientConn) InterceptorClient {
	return &interceptorClient{cc}
}

func (c *interceptorClient) OnRequest(ctx context.Context, in *OnRequestInput, opts ...grpc.CallOption) (*OnRequestOutput, error) {
	out := new(OnRequestOutput)
	err := c.cc.Invoke(ctx, "/proto.Interceptor/OnRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterceptorServer is the server API for Interceptor service.
type InterceptorServer interface {
	OnRequest(context.Context, *OnRequestInput) (*OnRequestOutput, error)
}

func RegisterInterceptorServer(s *grpc.Server, srv InterceptorServer) {
	s.RegisterService(&_Interceptor_serviceDesc, srv)
}

func _Interceptor_OnRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterceptorServer).OnRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Interceptor/OnRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterceptorServer).OnRequest(ctx, req.(*OnRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interceptor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Interceptor",
	HandlerType: (*InterceptorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnRequest",
			Handler:    _Interceptor_OnRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "http.proto",
}

func init() { proto.RegisterFile("http.proto", fileDescriptor_http_29fc2865f8068d5b) }

var fileDescriptor_http_29fc2865f8068d5b = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x18, 0xc5, 0x97, 0x76, 0xeb, 0x9f, 0x7d, 0xdd, 0x7f, 0x96, 0xa8, 0xa3, 0x0c, 0xc4, 0x52, 0x14,
	0x76, 0x21, 0xbd, 0xa8, 0x28, 0x3a, 0xbc, 0x19, 0x5a, 0xdc, 0x54, 0xdc, 0x08, 0xdd, 0x03, 0x74,
	0x5b, 0x60, 0xa2, 0xb6, 0x5d, 0x93, 0x0a, 0x7b, 0x2d, 0x1f, 0x41, 0x5f, 0x4c, 0x92, 0x66, 0x73,
	0xce, 0xa1, 0x37, 0x5e, 0xf5, 0x7c, 0xe4, 0x77, 0xfa, 0x9d, 0x84, 0x03, 0x30, 0xe5, 0x3c, 0xf5,
	0xd2, 0x2c, 0xe1, 0x09, 0xae, 0xc8, 0x8f, 0x7b, 0x0a, 0xf5, 0x7e, 0x4c, 0xe8, 0x2c, 0xa7, 0x8c,
	0xf7, 0xe2, 0x34, 0xe7, 0xf8, 0x00, 0xf4, 0x8c, 0xce, 0x6c, 0xe4, 0xa0, 0x96, 0xe9, 0xe3, 0x82,
	0xf6, 0xba, 0x61, 0x38, 0x50, 0x14, 0x11, 0xc7, 0xee, 0x3b, 0x82, 0xad, 0xa5, 0xb1, 0x9f, 0x73,
	0xe1, 0x3c, 0x01, 0x23, 0x1a, 0xf3, 0x87, 0x24, 0x96, 0xe6, 0xba, 0xbf, 0xa7, 0xcc, 0x6b, 0x9c,
	0xd7, 0x91, 0x10, 0x51, 0xf0, 0x62, 0xa1, 0xf6, 0xe3, 0x42, 0x7c, 0x28, 0x28, 0x66, 0xeb, 0x92,
	0xda, 0xfe, 0x42, 0xb1, 0x34, 0x89, 0x19, 0x15, 0x18, 0x73, 0x8f, 0xc0, 0x28, 0x7e, 0x8f, 0x01,
	0x8c, 0xde, 0xf5, 0x7d, 0x9f, 0x04, 0x56, 0x49, 0xe8, 0xe1, 0xe0, 0xaa, 0x13, 0x06, 0x16, 0x12,
	0x9a, 0x04, 0x37, 0xc1, 0x65, 0x68, 0x69, 0xee, 0x1b, 0x02, 0x73, 0x65, 0x13, 0x6e, 0x80, 0xf1,
	0x4c, 0xf9, 0x34, 0x99, 0xc8, 0x1b, 0x54, 0x89, 0x9a, 0xb0, 0x05, 0xfa, 0x90, 0xdc, 0xc9, 0x88,
	0x55, 0x22, 0x24, 0x3e, 0x87, 0x7f, 0x53, 0x1a, 0x4d, 0x68, 0xc6, 0xec, 0xb2, 0xa3, 0xb7, 0x4c,
	0x7f, 0xff, 0x7b, 0x70, 0xaf, 0x5b, 0x10, 0x41, 0xcc, 0xb3, 0x39, 0x59, 0xf0, 0x18, 0x43, 0x79,
	0x94, 0x4c, 0xe6, 0x76, 0xc5, 0x41, 0xad, 0x1a, 0x91, 0xba, 0xd9, 0x86, 0xda, 0x2a, 0x2c, 0x16,
	0x3e, 0xd2, 0xb9, 0x4a, 0x21, 0x24, 0xde, 0x81, 0xca, 0x4b, 0xf4, 0x94, 0x53, 0x15, 0xa2, 0x18,
	0xda, 0xda, 0x19, 0x72, 0x5f, 0x11, 0xd4, 0x56, 0x1f, 0x42, 0xdc, 0x82, 0xf1, 0x88, 0xe7, 0x4c,
	0xfa, 0xff, 0x13, 0x35, 0xe1, 0xf6, 0x67, 0x66, 0x4d, 0x66, 0x76, 0x36, 0x3c, 0xe3, 0x2f, 0xa1,
	0xf5, 0xbf, 0x09, 0xed, 0xdf, 0x82, 0xd9, 0x8b, 0x39, 0xcd, 0xc6, 0x34, 0xe5, 0x49, 0x86, 0x2f,
	0xa0, 0xba, 0x6c, 0x09, 0xde, 0x5d, 0xef, 0x8d, 0x2c, 0x66, 0xb3, 0xb1, 0xb9, 0x4e, 0x6e, 0x69,
	0x64, 0xc8, 0x83, 0xe3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0xd2, 0x6c, 0x8e, 0xe0, 0x02,
	0x00, 0x00,
}
